const wordSets = [
  {
    category: "People",
    words: [
      "Taylor Swift",
      "Cristiano Ronaldo",
      "Lionel Messi",
      "Elon Musk",
      "Shah Rukh Khan",
      "Dwayne Johnson",
      "Tom Cruise",
      "Leonardo DiCaprio",
      "Amitabh Bachchan",
      "Virat Kohli",
      "MS Dhoni",
      "Sachin Tendulkar",
      "Narendra Modi",
      "Bill Gates",
      "Mark Zuckerberg",
      "MrBeast",
      "Justin Bieber",
      "Selena Gomez",
      "Beyoncé",
      "Rihanna",
      "Lady Gaga",
      "Ariana Grande",
      "Kim Kardashian",
      "Kylie Jenner",
      "Jackie Chan",
      "Arnold Schwarzenegger",
      "Will Smith",
      "Johnny Depp",
      "Robert Downey Jr.",
      "Chris Hemsworth",
      "Tom Holland",
      "Zendaya",
      "Keanu Reeves",
      "Brad Pitt",
      "Angelina Jolie",
      "Jennifer Lopez",
      "Priyanka Chopra",
      "Deepika Padukone",
      "Alia Bhatt",
      "Salman Khan",
      "Aamir Khan",
      "Akshay Kumar",
      "Rajinikanth",
      "Ratan Tata",
      "Sundar Pichai",
      "Steve Jobs",
      "Jeff Bezos",
      "Walt Disney",
      "Ajay Devgn",
      "Ranbir Kapoor",
      "Ranveer Singh",
      "Hrithik Roshan",
      "Kareena Kapoor",
      "Katrina Kaif",
      "Madhuri Dixit",
      "Aishwarya Rai",
      "Rohit Sharma",
      "Neeraj Chopra",
      "Kapil Dev",
      "A. R. Rahman",
      "Arijit Singh",
      "Sonu Nigam",
      "Diljit Dosanjh",
      "Mukesh Ambani",
      "A. P. J. Abdul Kalam",
      "Mahatma Gandhi",
      "Sardar Patel",
      "Swami Vivekananda",
      "Dhirubhai Ambani",
      "Asha Bhosle",
      "Lata Mangeshkar",
      "Amit Trivedi",
      "Yo Yo Honey Singh",
      "Badshah",
      "CarryMinati",
      "Bhuvan Bam",
      "Ashish Chanchlani",
      "Elvish Yadav",
      "Samay Raina",
      "Munawar Faruqui",
      "Sandeep Maheshwari",
      "Kapil Sharma",
      "Amul",
      "Bhagat Singh",
      "Shivaji Maharaj",
    ],
  },
  {
    category: "Historical Figures",
    words: [
      "Mahatma Gandhi",
      "Albert Einstein",
      "Isaac Newton",
      "Napoleon",
      "Alexander the Great",
      "Julius Caesar",
      "Abraham Lincoln",
      "George Washington",
      "Nelson Mandela",
      "Martin Luther King Jr.",
      "Mother Teresa",
      "Leonardo da Vinci",
      "William Shakespeare",
      "Cleopatra",
      "Christopher Columbus",
      "Galileo Galilei",
      "Joan of Arc",
      "Winston Churchill",
      "Adolf Hitler",
      "Akbar",
      "Shivaji Maharaj",
      "Rani Lakshmibai",
      "Subhas Chandra Bose",
      "Jawaharlal Nehru",
      "Sardar Patel",
      "Bhagat Singh",
      "Tipu Sultan",
      "Ashoka",
      "Chandragupta Maurya",
      "Swami Vivekananda",
      "Marie Curie",
    ],
  },
  {
    category: "Scientists",
    words: [
      "Albert Einstein",
      "Isaac Newton",
      "Nikola Tesla",
      "Marie Curie",
      "Stephen Hawking",
      "Galileo Galilei",
      "Charles Darwin",
      "Thomas Edison",
      "Alexander Graham Bell",
      "Louis Pasteur",
      "Gregor Mendel",
      "Archimedes",
      "Alan Turing",
      "C. V. Raman",
      "A. P. J. Abdul Kalam",
      "Neil deGrasse Tyson",
      "James Watt",
      "Tim Berners-Lee",
      "Michael Faraday",
    ],
  },
  {
    category: "Cricketers",
    words: [
      "Virat Kohli",
      "MS Dhoni",
      "Sachin Tendulkar",
      "Rohit Sharma",
      "Jasprit Bumrah",
      "Hardik Pandya",
      "Ravindra Jadeja",
      "Shubman Gill",
      "Yuvraj Singh",
      "Kapil Dev",
      "Sourav Ganguly",
      "Rahul Dravid",
      "Anil Kumble",
      "Harbhajan Singh",
      "AB de Villiers",
      "Chris Gayle",
      "Babar Azam",
      "Ben Stokes",
      "Joe Root",
      "Steve Smith",
      "David Warner",
      "Pat Cummins",
      "Shane Warne",
      "Muttiah Muralitharan",
      "Kane Williamson",
      "Brian Lara",
      "Ricky Ponting",
      "Jacques Kallis",
      "Wasim Akram",
      "Imran Khan",
      "Lasith Malinga",
      "Andre Russell",
    ],
  },
  {
    category: "Footballers",
    words: [
      "Lionel Messi",
      "Cristiano Ronaldo",
      "Neymar",
      "Kylian Mbappe",
      "Erling Haaland",
      "Mohamed Salah",
      "Kevin De Bruyne",
      "Luka Modric",
      "Zinedine Zidane",
      "Ronaldinho",
      "Pele",
      "Diego Maradona",
      "David Beckham",
      "Wayne Rooney",
      "Harry Kane",
      "Jude Bellingham",
      "Vinicius Junior",
      "Karim Benzema",
      "Sergio Ramos",
      "Luis Suarez",
      "Andres Iniesta",
      "Xavi",
      "Son Heung-min",
    ],
  },
  {
    category: "F1 Drivers",
    words: [
      "Lewis Hamilton",
      "Max Verstappen",
      "Charles Leclerc",
      "Lando Norris",
      "Fernando Alonso",
      "Sebastian Vettel",
      "Michael Schumacher",
      "Ayrton Senna",
    ],
  },
  {
    category: "Athletes",
    words: [
      "Usain Bolt",
      "Michael Phelps",
      "Serena Williams",
      "Simone Biles",
      "LeBron James",
      "Michael Jordan",
      "Kobe Bryant",
      "Stephen Curry",
      "Roger Federer",
      "Rafael Nadal",
      "Novak Djokovic",
      "Neeraj Chopra",
      "Mary Kom",
      "P. V. Sindhu",
      "Saina Nehwal",
      "Abhinav Bindra",
      "Sachin Tendulkar",
      "Virat Kohli",
      "Cristiano Ronaldo",
      "Lionel Messi",
      "David Beckham",
      "Muhammad Ali",
    ],
  },
  {
    category: "Singers",
    words: [
      "Taylor Swift",
      "Michael Jackson",
      "Elvis Presley",
      "Beyonce",
      "Rihanna",
      "Adele",
      "Ed Sheeran",
      "Justin Bieber",
      "Bruno Mars",
      "The Weeknd",
      "Ariana Grande",
      "Lady Gaga",
      "Katy Perry",
      "Billie Eilish",
      "Drake",
      "Eminem",
      "Shakira",
      "Selena Gomez",
      "Bob Marley",
      "Freddie Mercury",
      "Harry Styles",
      "Arijit Singh",
      "Sonu Nigam",
      "Lata Mangeshkar",
      "Asha Bhosle",
      "Kishore Kumar",
      "Mohammed Rafi",
      "Shreya Ghoshal",
      "Sunidhi Chauhan",
      "Neha Kakkar",
      "Badshah",
      "Diljit Dosanjh",
      "Honey Singh",
      "Kumar Sanu",
      "Udit Narayan",
      "Alka Yagnik",
      "Shaan",
      "KK",
      "Sonu Kakkar",
      "Darshan Raval",
      "Guru Randhawa",
      "Jubin Nautiyal",
      "Ankit Tiwari",
      "Atif Aslam",
      "A. R. Rahman",
      "B Praak",
      "King",
      "AP Dhillon",
      "Karan Aujla",
    ],
  },
  {
    category: "Bands",
    words: [
      "The Beatles",
      "Queen",
      "Coldplay",
      "Maroon 5",
      "Linkin Park",
      "Imagine Dragons",
      "OneRepublic",
      "ABBA",
      "Backstreet Boys",
      "One Direction",
      "BTS",
      "BLACKPINK",
      "Red Hot Chili Peppers",
      "Metallica",
      "Nirvana",
      "Guns N' Roses",
      "Pink Floyd",
      "Bon Jovi",
    ],
  },
  {
    category: "Comedians",
    words: [
      "Charlie Chaplin",
      "Mr. Bean",
      "Jim Carrey",
      "Kevin Hart",
      "Rowan Atkinson",
      "Eddie Murphy",
      "Steve Carell",
      "Adam Sandler",
      "Jack Black",
      "Will Ferrell",
      "Kapil Sharma",
      "Zakir Khan",
      "Vir Das",
      "Samay Raina",
      "Tanmay Bhat",
    ],
  },
  {
    category: "YouTubers",
    words: [
      "MrBeast",
      "PewDiePie",
      "Logan Paul",
      "Jake Paul",
      "KSI",
      "Dude Perfect",
      "Kai Cenat",
      "IShowSpeed",
      "Sidemen",
      "Lilly Singh",
      "MKBHD",
      "Zach King",
      "Khaby Lame",
      "Cocomelon",
      "Dream",
      "CarryMinati",
      "Bhuvan Bam",
      "Ashish Chanchlani",
      "Amit Bhadana",
      "Sandeep Maheshwari",
      "Technical Guruji",
      "BB Ki Vines",
      "Round2hell",
      "Triggered Insaan",
      "Total Gaming",
      "Techno Gamerz",
      "BeastBoyShub",
      "Slayy Point",
      "Harsh Beniwal",
      "Flying Beast",
      "Dhruv Rathee",
      "Anurag Dobhal",
      "Elvish Yadav",
      "Munawar Faruqui",
      "Thugesh",
      "Mr Indian Hacker",
      "Village Cooking Channel",
      "KL Bro Biju",
    ],
  },
  {
    category: "Movies",
    words: [
      "Titanic",
      "Avatar",
      "Avengers: Endgame",
      "The Dark Knight",
      "Harry Potter",
      "Jurassic Park",
      "The Lion King",
      "Frozen",
      "Toy Story",
      "The Matrix",
      "Home Alone",
      "Forrest Gump",
      "The Godfather",
      "Spider-Man",
      "Iron Man",
      "Black Panther",
      "Interstellar",
      "Inception",
      "Joker",
      "Barbie",
      "Oppenheimer",
      "Top Gun",
      "Gladiator",
      "Pirates of the Caribbean",
      "The Lord of the Rings",
      "Star Wars",
      "The Hunger Games",
      "Mission: Impossible",
      "Fast & Furious",
      "The Avengers",
      "Deadpool",
      "Shrek",
      "3 Idiots",
      "Dangal",
      "PK",
      "Lagaan",
      "Sholay",
      "Dilwale Dulhania Le Jayenge",
      "Kabhi Khushi Kabhie Gham",
      "Zindagi Na Milegi Dobara",
      "Yeh Jawaani Hai Deewani",
      "Chennai Express",
      "Bajrangi Bhaijaan",
      "Pathaan",
      "Jawan",
      "War",
      "Gully Boy",
      "Drishyam",
      "Andhadhun",
      "Bhool Bhulaiyaa",
      "Krrish",
      "Don",
      "Om Shanti Om",
      "Rockstar",
      "Barfi!",
      "Queen",
      "Taare Zameen Par",
      "Munna Bhai M.B.B.S.",
      "Hera Pheri",
      "Welcome",
      "Bhool Bhulaiyaa 2",
      "Stree",
      "The Batman",
      "Top Gun: Maverick",
      "The Wolf of Wall Street",
      "The Hangover",
      "Moana",
      "Finding Nemo",
      "The Incredibles",
      "Coco",
      "Despicable Me",
      "Spider-Man: No Way Home",
    ],
  },
  {
    category: "TV Shows",
    words: [
      "Friends",
      "The Office",
      "Breaking Bad",
      "Game of Thrones",
      "Stranger Things",
      "Wednesday",
      "Squid Game",
      "Money Heist",
      "Sherlock",
      "The Big Bang Theory",
      "How I Met Your Mother",
      "The Simpsons",
      "Family Guy",
      "South Park",
      "The Walking Dead",
      "Peaky Blinders",
      "Prison Break",
      "Dark",
      "The Boys",
      "Black Mirror",
      "House of the Dragon",
      "The Mandalorian",
      "Cobra Kai",
      "The Last of Us",
      "Bridgerton",
      "The Witcher",
      "Narcos",
      "Lost",
      "Suits",
      "Taarak Mehta Ka Ooltah Chashmah",
      "CID",
      "Bigg Boss",
      "Kaun Banega Crorepati",
      "Indian Idol",
      "The Kapil Sharma Show",
      "Shark Tank India",
      "Khatron Ke Khiladi",
      "Splitsvilla",
      "Roadies",
      "Panchayat",
      "Mirzapur",
      "Sacred Games",
      "Scam 1992",
      "Kota Factory",
      "Family Man",
      "Paatal Lok",
      "Aspirants",
      "Gullak",
      "TVF Pitchers",
      "Farzi",
      "Indian Matchmaking",
      "Made in Heaven",
      "Delhi Crime",
    ],
  },
  {
    category: "Characters",
    words: [
      "Harry Potter",
      "Sherlock Holmes",
      "James Bond",
      "Mr. Bean",
      "Jack Sparrow",
      "Forrest Gump",
      "Rocky Balboa",
      "Indiana Jones",
      "Walter White",
      "Michael Scott",
      "Wednesday Addams",
      "Eleven",
      "Tony Stark",
      "Peter Parker",
      "Bruce Wayne",
      "Clark Kent",
      "Darth Vader",
      "Luke Skywalker",
      "Yoda",
      "Gollum",
      "Shrek",
      "Homer Simpson",
      "Bart Simpson",
      "Mickey Mouse",
      "Donald Duck",
      "Tom",
      "Jerry",
      "Scooby-Doo",
      "SpongeBob",
      "Barbie",
    ],
  },
  {
    category: "Superheroes",
    words: [
      "Spider-Man",
      "Iron Man",
      "Batman",
      "Superman",
      "Hulk",
      "Thor",
      "Captain America",
      "Black Panther",
      "Wonder Woman",
      "Flash",
      "Aquaman",
      "Doctor Strange",
      "Deadpool",
      "Wolverine",
      "Captain Marvel",
      "Ant-Man",
      "Black Widow",
      "Hawkeye",
      "Green Lantern",
      "Supergirl",
      "Shazam",
      "Venom",
      "Star-Lord",
      "Groot",
      "Storm",
      "Professor X",
      "Cyclops",
      "Daredevil",
    ],
  },
  {
    category: "Villains",
    words: [
      "Thanos",
      "Joker",
      "Darth Vader",
      "Voldemort",
      "Scar",
      "Loki",
      "Ursula",
      "Maleficent",
      "Cruella",
      "Sauron",
      "Green Goblin",
      "Venom",
      "Ultron",
      "Magneto",
      "Hannibal Lecter",
      "Norman Bates",
      "Agent Smith",
      "Bane",
      "Harley Quinn",
      "Hades",
      "Lord Farquaad",
      "Bowser",
      "Cruella de Vil",
      "Davy Jones",
    ],
  },
  {
    category: "Disney Characters",
    words: [
      "Mickey Mouse",
      "Minnie Mouse",
      "Donald Duck",
      "Goofy",
      "Pluto",
      "Simba",
      "Mufasa",
      "Scar",
      "Elsa",
      "Anna",
      "Olaf",
      "Ariel",
      "Cinderella",
      "Snow White",
      "Belle",
      "Aladdin",
      "Genie",
      "Jasmine",
      "Woody",
      "Buzz Lightyear",
      "Stitch",
      "Winnie the Pooh",
      "Tinker Bell",
      "Peter Pan",
      "Dumbo",
      "Nemo",
      "Dory",
      "Lightning McQueen",
      "Mater",
    ],
  },
  {
    category: "Countries",
    words: [
      "India",
      "United States",
      "United Kingdom",
      "Canada",
      "Australia",
      "Japan",
      "China",
      "South Korea",
      "Russia",
      "France",
      "Germany",
      "Italy",
      "Spain",
      "Brazil",
      "Argentina",
      "Mexico",
      "Egypt",
      "South Africa",
      "New Zealand",
      "Singapore",
      "Thailand",
      "Indonesia",
      "Malaysia",
      "Saudi Arabia",
      "UAE",
      "Turkey",
      "Switzerland",
      "Greece",
      "Portugal",
      "Nepal",
      "Sri Lanka",
      "Pakistan",
      "Bangladesh",
      "Afghanistan",
      "Maldives",
      "North Korea",
      "Ukraine",
      "Netherlands",
      "Belgium",
      "Austria",
      "Ireland",
      "Iceland",
      "Norway",
      "Sweden",
      "Denmark",
      "Finland",
      "Poland",
      "Czech Republic",
      "Hungary",
      "Romania",
      "Croatia",
      "Serbia",
      "Georgia",
      "United Arab Emirates",
      "Qatar",
      "Kuwait",
      "Oman",
      "Israel",
      "Jordan",
      "Iran",
      "Iraq",
      "Bhutan",
      "Myanmar",
      "Vietnam",
      "Cambodia",
      "Laos",
      "Philippines",
      "Mongolia",
      "Kazakhstan",
      "Uzbekistan",
      "Morocco",
      "Nigeria",
      "Kenya",
      "Tanzania",
      "Ethiopia",
      "Ghana",
      "Uganda",
      "Algeria",
      "Tunisia",
      "Chile",
      "Peru",
      "Colombia",
      "Venezuela",
      "Uruguay",
      "Ecuador",
      "Bolivia",
      "Paraguay",
      "Costa Rica",
      "Panama",
      "Cuba",
      "Jamaica",
      "Bahamas",
      "Dominican Republic",
      "Fiji",
      "Samoa",
      "Mauritius",
      "Seychelles",
    ],
  },
  {
    category: "Cities",
    words: [
      "Mumbai",
      "Delhi",
      "New York",
      "London",
      "Paris",
      "Tokyo",
      "Dubai",
      "Singapore",
      "Los Angeles",
      "Las Vegas",
      "Rome",
      "Barcelona",
      "Madrid",
      "Sydney",
      "Melbourne",
      "Toronto",
      "San Francisco",
      "Chicago",
      "Washington D.C.",
      "Amsterdam",
      "Berlin",
      "Moscow",
      "Istanbul",
      "Bangkok",
      "Seoul",
      "Hong Kong",
      "Venice",
      "Rio de Janeiro",
      "Cairo",
      "Jaipur",
      "Bengaluru",
      "Hyderabad",
      "Chennai",
      "Kolkata",
      "Pune",
      "Ahmedabad",
      "Surat",
      "Lucknow",
      "Kanpur",
      "Nagpur",
      "Indore",
      "Bhopal",
      "Patna",
      "Chandigarh",
      "Nashik",
      "Thane",
      "Navi Mumbai",
      "Dombivli",
      "Agra",
      "Varanasi",
      "Amritsar",
      "Goa",
      "Kochi",
      "Mysore",
      "Srinagar",
      "Ranchi",
      "Vadodara",
      "New Delhi",
      "Mysuru",
      "Rajkot",
      "Aurangabad",
      "Ludhiana",
      "Bhubaneswar",
      "Dehradun",
      "Guwahati",
      "Noida",
      "Gurugram",
      "Faridabad",
      "Meerut",
      "Visakhapatnam",
      "Vijayawada",
      "Coimbatore",
      "Madurai",
      "Mangaluru",
      "Thiruvananthapuram",
      "Miami",
      "Boston",
      "Seattle",
      "Houston",
      "Dallas",
      "Vancouver",
      "Mexico City",
      "Havana",
      "Manchester",
      "Liverpool",
      "Edinburgh",
      "Dublin",
      "Munich",
      "Brussels",
      "Zurich",
      "Vienna",
      "Prague",
      "Budapest",
      "Warsaw",
      "Milan",
      "Florence",
      "Lisbon",
      "Athens",
      "Kyiv",
      "Abu Dhabi",
      "Doha",
      "Riyadh",
      "Jeddah",
      "Cape Town",
      "Johannesburg",
      "Nairobi",
      "Lagos",
      "Osaka",
      "Kyoto",
      "Beijing",
      "Shanghai",
      "Jakarta",
      "Kuala Lumpur",
      "Manila",
      "Bali",
      "Auckland",
      "São Paulo",
      "Buenos Aires",
      "Lima",
      "Santiago",
    ],
  },
  {
    category: "Landmarks",
    words: [
      "Taj Mahal",
      "Eiffel Tower",
      "Statue of Liberty",
      "Burj Khalifa",
      "Great Wall of China",
      "Big Ben",
      "Colosseum",
      "Pyramids of Giza",
      "Sydney Opera House",
      "Golden Gate Bridge",
      "Christ the Redeemer",
      "Machu Picchu",
      "Mount Everest",
      "Leaning Tower of Pisa",
      "London Eye",
      "Empire State Building",
      "Times Square",
      "Stonehenge",
      "Gateway of India",
      "India Gate",
      "Red Fort",
      "Qutub Minar",
      "Charminar",
      "Victoria Memorial",
      "Marina Bay Sands",
      "Hollywood Sign",
      "Niagara Falls",
      "Grand Canyon",
      "Sagrada Familia",
      "Burj Al Arab",
    ],
  },
  {
    category: "Tourist Places",
    words: [
      "Goa",
      "Paris",
      "Dubai",
      "Maldives",
      "Switzerland",
      "Bali",
      "London",
      "New York",
      "Tokyo",
      "Singapore",
      "Thailand",
      "Australia",
      "Venice",
      "Rome",
      "Barcelona",
      "Hawaii",
      "Istanbul",
      "Egypt",
      "Amsterdam",
      "Kashmir",
      "Manali",
      "Shimla",
      "Kerala",
      "Rajasthan",
      "Ladakh",
      "Andaman",
      "Darjeeling",
      "Agra",
      "Varanasi",
      "Ooty",
    ],
  },
  {
    category: "Food",
    words: [
      "Pizza",
      "Burger",
      "French Fries",
      "Pasta",
      "Sushi",
      "Tacos",
      "Sandwich",
      "Noodles",
      "Fried Chicken",
      "Ice Cream",
      "Chocolate",
      "Cake",
      "Donut",
      "Popcorn",
      "Pancakes",
      "Waffles",
      "Hot Dog",
      "Steak",
      "Nachos",
      "Lasagna",
      "Biryani",
      "Dosa",
      "Samosa",
      "Pav Bhaji",
      "Momos",
      "Chole Bhature",
      "Butter Chicken",
      "Paneer",
      "Maggi",
      "Pani Puri",
      "Vada Pav",
      "Idli",
      "Gulab Jamun",
      "Jalebi",
      "Rasgulla",
      "Paneer Tikka",
      "Palak Paneer",
      "Masala Dosa",
      "Poha",
      "Misal Pav",
      "Rajma Chawal",
      "Dal Makhani",
      "Naan",
      "Tandoori Chicken",
      "Aloo Paratha",
      "Chole",
      "Kheer",
      "Lassi",
      "Dhokla",
      "Kachori",
      "Pakora",
      "Upma",
      "Thali",
      "Shawarma",
      "Doner Kebab",
      "Ramen",
      "Curry",
    ],
  },
  {
    category: "Fast Food",
    words: [
      "McDonald's",
      "KFC",
      "Burger King",
      "Subway",
      "Pizza Hut",
      "Domino's",
      "Starbucks",
      "Taco Bell",
      "Wendy's",
      "Dunkin'",
      "Burger",
      "Pizza",
      "French Fries",
      "Nuggets",
      "Hot Dog",
      "Tacos",
      "Nachos",
      "Sandwich",
      "Fried Chicken",
      "Milkshake",
      "Donut",
      "Popcorn",
      "Wrap",
      "Momos",
      "Shawarma",
    ],
  },
  {
    category: "Desserts",
    words: [
      "Ice Cream",
      "Chocolate",
      "Cake",
      "Donut",
      "Brownie",
      "Cheesecake",
      "Cupcake",
      "Gulab Jamun",
      "Jalebi",
      "Rasgulla",
      "Kheer",
      "Kulfi",
      "Muffin",
      "Pudding",
      "Cookies",
      "Waffle",
      "Pancake",
      "Lava Cake",
      "Caramel",
      "Lollipop",
      "Candy",
      "Doughnut",
      "Falooda",
    ],
  },
  {
    category: "Fruits",
    words: [
      "Apple",
      "Banana",
      "Mango",
      "Orange",
      "Grapes",
      "Watermelon",
      "Pineapple",
      "Strawberry",
      "Papaya",
      "Guava",
      "Pomegranate",
      "Coconut",
      "Kiwi",
      "Peach",
      "Pear",
      "Cherry",
      "Lemon",
      "Lime",
      "Avocado",
      "Dragon Fruit",
      "Jackfruit",
      "Lychee",
      "Blueberry",
      "Raspberry",
      "Melon",
      "Fig",
      "Dates",
      "Plum",
      "Apricot",
    ],
  },
  {
    category: "Drinks",
    words: [
      "Coca-Cola",
      "Pepsi",
      "Sprite",
      "Fanta",
      "Red Bull",
      "Monster",
      "7UP",
      "Mountain Dew",
      "Mirinda",
      "Thumbs Up",
      "Limca",
      "Maaza",
      "Frooti",
      "Paper Boat",
      "Gatorade",
      "Coffee",
      "Tea",
      "Lemonade",
      "Milkshake",
      "Hot Chocolate",
      "Orange Juice",
      "Apple Juice",
      "Coconut Water",
      "Lassi",
      "Smoothie",
      "Thums Up",
      "Starbucks",
      "Chai",
      "Mango Lassi",
      "Masala Chai",
      "Cold Coffee",
    ],
  },
  {
    category: "Brands",
    words: [
      "Apple",
      "Nike",
      "Adidas",
      "Coca-Cola",
      "Pepsi",
      "McDonald's",
      "KFC",
      "Samsung",
      "Google",
      "Microsoft",
      "Amazon",
      "Netflix",
      "Disney",
      "Lego",
      "Puma",
      "Gucci",
      "Louis Vuitton",
      "Chanel",
      "Rolex",
      "Toyota",
      "BMW",
      "Mercedes-Benz",
      "Ferrari",
      "Lamborghini",
      "Porsche",
      "Starbucks",
      "Red Bull",
      "Sony",
      "IKEA",
    ],
  },
  {
    category: "Car Brands",
    words: [
      "Toyota",
      "BMW",
      "Mercedes-Benz",
      "Audi",
      "Ferrari",
      "Lamborghini",
      "Porsche",
      "Ford",
      "Honda",
      "Hyundai",
      "Tesla",
      "Volkswagen",
      "Nissan",
      "Kia",
      "Jeep",
      "Rolls-Royce",
      "Bentley",
      "Mahindra",
      "Tata",
      "Maruti Suzuki",
      "Skoda",
    ],
  },
  {
    category: "Cars",
    words: [
      "Tesla Model 3",
      "Ford Mustang",
      "Mercedes G-Wagon",
      "Jeep Wrangler",
      "Range Rover",
      "Porsche 911",
      "Lamborghini Urus",
      "Bugatti Chiron",
      "Rolls-Royce Phantom",
      "Toyota Fortuner",
      "Mahindra Thar",
      "Tata Safari",
      "Maruti Swift",
      "Honda City",
      "Hyundai Creta",
      "Kia Seltos",
      "Mini Cooper",
    ],
  },
  {
    category: "Sports",
    words: [
      "Cricket",
      "Football",
      "Basketball",
      "Tennis",
      "Badminton",
      "Hockey",
      "Boxing",
      "Wrestling",
      "Golf",
      "Swimming",
      "Athletics",
      "Formula 1",
      "Volleyball",
      "Table Tennis",
      "Baseball",
      "Rugby",
      "Cycling",
      "Gymnastics",
      "Skateboarding",
      "Skiing",
      "Archery",
      "Kabaddi",
      "Chess",
      "Surfing",
    ],
  },
  {
    category: "Cricket Teams",
    words: [
      "India",
      "Australia",
      "England",
      "Pakistan",
      "South Africa",
      "New Zealand",
      "Sri Lanka",
      "West Indies",
      "Bangladesh",
      "Afghanistan",
      "Mumbai Indians",
      "Chennai Super Kings",
      "Royal Challengers Bengaluru",
      "Kolkata Knight Riders",
      "Rajasthan Royals",
      "Delhi Capitals",
      "Punjab Kings",
      "Sunrisers Hyderabad",
      "Gujarat Titans",
      "Lucknow Super Giants",
    ],
  },
  {
    category: "Football Teams",
    words: [
      "Real Madrid",
      "Barcelona",
      "Manchester United",
      "Manchester City",
      "Liverpool",
      "Arsenal",
      "Chelsea",
      "Bayern Munich",
      "PSG",
      "Juventus",
      "Brazil",
      "Argentina",
      "France",
      "Germany",
      "Portugal",
      "Spain",
      "England",
      "India",
    ],
  },
  {
    category: "Sports Equipment",
    words: [
      "Cricket Bat",
      "Cricket Ball",
      "Football",
      "Basketball",
      "Tennis Racket",
      "Badminton Racket",
      "Hockey Stick",
      "Golf Club",
      "Boxing Gloves",
      "Helmet",
      "Goalpost",
      "Tennis Ball",
      "Shuttlecock",
      "Skateboard",
      "Bicycle",
      "Swimming Goggles",
      "Baseball Bat",
      "Baseball Glove",
      "Dumbbell",
      "Yoga Mat",
    ],
  },
  {
    category: "Animals",
    words: [
      "Dog",
      "Cat",
      "Lion",
      "Tiger",
      "Elephant",
      "Horse",
      "Cow",
      "Monkey",
      "Giraffe",
      "Zebra",
      "Bear",
      "Wolf",
      "Fox",
      "Deer",
      "Rabbit",
      "Panda",
      "Kangaroo",
      "Penguin",
      "Dolphin",
      "Whale",
      "Shark",
      "Crocodile",
      "Snake",
      "Gorilla",
      "Leopard",
      "Cheetah",
      "Camel",
      "Goat",
      "Sheep",
      "Pig",
      "Chicken",
      "Donkey",
      "Koala",
      "Hippopotamus",
      "Rhinoceros",
    ],
  },
  {
    category: "Birds",
    words: [
      "Eagle",
      "Parrot",
      "Peacock",
      "Owl",
      "Pigeon",
      "Crow",
      "Sparrow",
      "Penguin",
      "Flamingo",
      "Swan",
      "Ostrich",
      "Duck",
      "Hen",
      "Turkey",
      "Kingfisher",
      "Woodpecker",
      "Hawk",
      "Falcon",
      "Vulture",
      "Seagull",
      "Parakeet",
      "Hummingbird",
      "Pelican",
    ],
  },
  {
    category: "Professions",
    words: [
      "Doctor",
      "Teacher",
      "Engineer",
      "Police Officer",
      "Firefighter",
      "Pilot",
      "Chef",
      "Lawyer",
      "Actor",
      "Singer",
      "Athlete",
      "Journalist",
      "Photographer",
      "Scientist",
      "Farmer",
      "Nurse",
      "Dentist",
      "Architect",
      "Mechanic",
      "Driver",
      "Soldier",
      "Judge",
      "Artist",
      "Musician",
      "Writer",
      "Director",
      "Astronaut",
      "Businessman",
      "Designer",
      "Electrician",
    ],
  },
  {
    category: "Household Items",
    words: [
      "Chair",
      "Table",
      "Bed",
      "Sofa",
      "Television",
      "Refrigerator",
      "Washing Machine",
      "Fan",
      "Air Conditioner",
      "Microwave",
      "Clock",
      "Mirror",
      "Lamp",
      "Pillow",
      "Blanket",
      "Curtain",
      "Broom",
      "Bucket",
      "Iron",
      "Vacuum Cleaner",
      "Remote Control",
      "Door",
      "Window",
      "Cupboard",
      "Fridge",
      "Toaster",
      "Kettle",
      "Plate",
      "Spoon",
      "Bottle",
    ],
  },
  {
    category: "School Items",
    words: [
      "Pen",
      "Pencil",
      "Notebook",
      "Eraser",
      "Sharpener",
      "Ruler",
      "School Bag",
      "Calculator",
      "Blackboard",
      "Chalk",
      "Desk",
      "Chair",
      "Book",
      "Backpack",
      "Compass",
      "Protractor",
      "Glue",
      "Scissors",
      "Marker",
      "Highlighter",
      "Lunchbox",
      "Water Bottle",
      "Uniform",
      "Textbook",
      "Stapler",
    ],
  },
  {
    category: "Musical Instruments",
    words: [
      "Guitar",
      "Piano",
      "Drums",
      "Violin",
      "Flute",
      "Trumpet",
      "Saxophone",
      "Harmonica",
      "Keyboard",
      "Tabla",
      "Sitar",
      "Ukulele",
      "Cello",
      "Clarinet",
      "Harp",
      "Accordion",
      "Conga",
      "Banjo",
      "Xylophone",
      "Tambourine",
    ],
  },
  {
    category: "Vehicles",
    words: [
      "Car",
      "Bus",
      "Train",
      "Airplane",
      "Helicopter",
      "Motorcycle",
      "Scooter",
      "Bicycle",
      "Truck",
      "Taxi",
      "Auto Rickshaw",
      "Boat",
      "Ship",
      "Submarine",
      "Rocket",
      "Tram",
      "Metro",
      "Van",
      "Ambulance",
      "Fire Truck",
      "Police Car",
      "School Bus",
      "Yacht",
      "Cruise Ship",
    ],
  },
  {
    category: "Clothing",
    words: [
      "T-Shirt",
      "Jeans",
      "Shirt",
      "Trousers",
      "Shorts",
      "Jacket",
      "Hoodie",
      "Sweater",
      "Dress",
      "Skirt",
      "Suit",
      "Tie",
      "Saree",
      "Kurta",
      "Sherwani",
      "Lehenga",
      "Shoes",
      "Sneakers",
      "Boots",
      "Sandals",
      "Cap",
      "Hat",
      "Scarf",
      "Gloves",
      "Sunglasses",
    ],
  },
  {
    category: "Toys",
    words: [
      "LEGO",
      "Barbie",
      "Hot Wheels",
      "Teddy Bear",
      "Rubik's Cube",
      "Yo-Yo",
      "Ludo",
      "Chess",
      "Monopoly",
      "UNO",
      "Nerf Gun",
      "Remote Control Car",
      "Toy Train",
      "Action Figure",
      "Doll",
      "Puzzle",
      "Frisbee",
      "Kite",
      "Play-Doh",
      "Slinky",
      "Spinning Top",
      "Toy Robot",
      "Jigsaw Puzzle",
      "Building Blocks",
    ],
  },
  {
    category: "Nature",
    words: [
      "Mountain",
      "River",
      "Ocean",
      "Waterfall",
      "Forest",
      "Desert",
      "Beach",
      "Volcano",
      "Island",
      "Lake",
      "Rainbow",
      "Cloud",
      "Rain",
      "Snow",
      "Thunder",
      "Lightning",
      "Sun",
      "Moon",
      "Star",
      "Tree",
      "Flower",
      "Grass",
      "Fire",
      "Wind",
      "Storm",
    ],
  },
  {
    category: "Space",
    words: [
      "Sun",
      "Moon",
      "Earth",
      "Mars",
      "Jupiter",
      "Saturn",
      "Venus",
      "Mercury",
      "Neptune",
      "Uranus",
      "Pluto",
      "Galaxy",
      "Milky Way",
      "Black Hole",
      "Astronaut",
      "Rocket",
      "Spaceship",
      "Alien",
      "Meteor",
      "Comet",
      "Asteroid",
      "International Space Station",
      "Solar System",
      "Star",
      "Moon Landing",
    ],
  },
  {
    category: "Internet Classics",
    words: [
      "Rickroll",
      "Doge",
      "Trollface",
      "Grumpy Cat",
      "Success Kid",
      "This Is Fine",
      "Distracted Boyfriend",
      "Woman Yelling at a Cat",
      "Drake Hotline Bling",
      "Pepe the Frog",
      "Nyan Cat",
      "Mocking SpongeBob",
      "Expanding Brain",
      "Roll Safe",
      "Change My Mind",
      "Coffin Dance",
      "Harlem Shake",
      "Gangnam Style",
      "Charlie Bit My Finger",
      "Keyboard Cat",
      "Troll Face",
    ],
  },
  {
    category: "Viral Trends",
    words: [
      "Skibidi Toilet",
      "Sigma",
      "Rizz",
      "Fanum Tax",
      "Hawk Tuah",
      "Ohio",
      "Grimace Shake",
      "NPC",
      "Mewing",
      "Looksmaxxing",
      "Aura Farming",
      "Brain Rot",
      "Locked In",
      "Cooked",
      "Crash Out",
      "Delulu",
      "Chill Guy",
      "Among Us",
      "Backrooms",
      "Let Him Cook",
    ],
  },
  {
    category: "Trending 2026",
    words: [
      "6-7",
      "Aura Farming",
      "Cooked",
      "Crash Out",
      "Locked In",
      "Brain Rot",
      "Aura",
      "Rizz",
      "Sigma",
      "Delulu",
      "NPC",
      "Skibidi Toilet",
      "Fanum Tax",
      "Hawk Tuah",
      "Ohio",
      "Mewing",
      "Looksmaxxing",
      "Chill Guy",
      "Among Us",
      "Backrooms",
      "Let Him Cook",
      "We Are So Back",
      "Sus",
      "Gyatt",
    ],
  },
  {
    category: "Internet Personalities",
    words: [
      "MrBeast",
      "PewDiePie",
      "KSI",
      "Logan Paul",
      "Jake Paul",
      "IShowSpeed",
      "Kai Cenat",
      "Khaby Lame",
      "Zach King",
      "Mark Rober",
      "MKBHD",
      "Dream",
      "Snoop Dogg",
      "CarryMinati",
      "Bhuvan Bam",
      "Ashish Chanchlani",
      "Amit Bhadana",
      "Elvish Yadav",
      "Munawar Faruqui",
      "Samay Raina",
      "Tanmay Bhat",
      "Zakir Khan",
      "Triggered Insaan",
      "Harsh Beniwal",
      "Thugesh",
      "Flying Beast",
      "Sourav Joshi",
      "Dhruv Rathee",
      "BeastBoyShub",
      "Techno Gamerz",
      "Total Gaming",
      "Mr Indian Hacker",
      "Sandeep Maheshwari",
      "Ranveer Allahbadia",
      "Ashneer Grover",
    ],
  },
  {
    category: "Restaurants",
    words: [
      "McDonald's",
      "KFC",
      "Burger King",
      "Subway",
      "Pizza Hut",
      "Domino's",
      "Starbucks",
      "Taco Bell",
      "Dunkin'",
      "Baskin-Robbins",
      "Barbeque Nation",
      "Haldiram's",
      "Bikanervala",
      "Saravana Bhavan",
      "Wow! Momo",
      "Cafe Coffee Day",
    ],
  },
  {
    category: "Airlines",
    words: [
      "Air India",
      "IndiGo",
      "Emirates",
      "Qatar Airways",
      "Singapore Airlines",
      "British Airways",
      "Lufthansa",
      "Air France",
      "Etihad Airways",
      "Vistara",
      "Japan Airlines",
      "Turkish Airlines",
    ],
  },
  {
    category: "Buildings",
    words: [
      "Burj Khalifa",
      "Taj Mahal",
      "Eiffel Tower",
      "Empire State Building",
      "Big Ben",
      "Sydney Opera House",
      "White House",
      "Buckingham Palace",
      "Colosseum",
      "Leaning Tower of Pisa",
      "Gateway of India",
      "India Gate",
      "Red Fort",
      "Qutub Minar",
      "Charminar",
      "Victoria Memorial",
      "Marina Bay Sands",
      "Burj Al Arab",
      "Petronas Towers",
      "One World Trade Center",
    ],
  },
  {
    category: "Colors",
    words: [
      "Red",
      "Blue",
      "Green",
      "Yellow",
      "Orange",
      "Purple",
      "Pink",
      "Black",
      "White",
      "Brown",
      "Grey",
      "Gold",
      "Silver",
      "Violet",
      "Indigo",
      "Turquoise",
      "Maroon",
      "Navy Blue",
      "Sky Blue",
      "Lime",
      "Beige",
      "Cyan",
    ],
  },
];
