const wordSets = [
  /* =====================================================
       FAMOUS PEOPLE
    ===================================================== */

  {
    category: "Famous People",
    words: [
      "Albert Einstein",
      "Michael Jackson",
      "Cristiano Ronaldo",
      "Lionel Messi",
      "Taylor Swift",
      "Elon Musk",
      "Bill Gates",
      "Steve Jobs",
      "Dwayne Johnson",
      "Tom Cruise",
      "Leonardo DiCaprio",
      "Jackie Chan",
      "Brad Pitt",
      "Will Smith",
      "Johnny Depp",
      "Charlie Chaplin",
      "Walt Disney",
      "Nelson Mandela",
      "Mahatma Gandhi",
      "Abraham Lincoln",
      "Queen Elizabeth II",
      "Donald Trump",
      "Barack Obama",
      "Albert Einstein",
      "Pablo Picasso",
      "William Shakespeare",
      "Nikola Tesla",
      "Stephen Hawking",
      "Isaac Newton",
      "Bruce Lee",
    ],
  },

  /* =====================================================
       ACTORS
    ===================================================== */

  {
    category: "Actors",
    words: [
      "Tom Cruise",
      "Leonardo DiCaprio",
      "Brad Pitt",
      "Johnny Depp",
      "Will Smith",
      "Dwayne Johnson",
      "Robert Downey Jr.",
      "Chris Hemsworth",
      "Chris Evans",
      "Ryan Reynolds",
      "Keanu Reeves",
      "Jackie Chan",
      "Jim Carrey",
      "Arnold Schwarzenegger",
      "Sylvester Stallone",
      "Tom Hanks",
      "Morgan Freeman",
      "Hugh Jackman",
      "Matt Damon",
      "Christian Bale",
      "Mark Wahlberg",
      "Jason Statham",
      "Adam Sandler",
      "Rowan Atkinson",
      "Daniel Radcliffe",
      "Johnny Depp",
      "Benedict Cumberbatch",
      "Pedro Pascal",
      "Cillian Murphy",
      "Joaquin Phoenix",
    ],
  },

  /* =====================================================
       ACTRESSES
    ===================================================== */

  {
    category: "Actresses",
    words: [
      "Angelina Jolie",
      "Jennifer Lawrence",
      "Emma Watson",
      "Emma Stone",
      "Scarlett Johansson",
      "Anne Hathaway",
      "Natalie Portman",
      "Margot Robbie",
      "Gal Gadot",
      "Zendaya",
      "Jennifer Aniston",
      "Julia Roberts",
      "Sandra Bullock",
      "Meryl Streep",
      "Nicole Kidman",
      "Cameron Diaz",
      "Megan Fox",
      "Millie Bobby Brown",
      "Jenna Ortega",
      "Kristen Stewart",
      "Amanda Seyfried",
      "Reese Witherspoon",
      "Halle Berry",
      "Cate Blanchett",
      "Emily Blunt",
      "Florence Pugh",
      "Dakota Johnson",
      "Natalie Portman",
      "Charlize Theron",
      "Sydney Sweeney",
    ],
  },

  /* =====================================================
       BOLLYWOOD ACTORS
    ===================================================== */

  {
    category: "Bollywood Actors",
    words: [
      "Shah Rukh Khan",
      "Salman Khan",
      "Aamir Khan",
      "Amitabh Bachchan",
      "Akshay Kumar",
      "Ajay Devgn",
      "Hrithik Roshan",
      "Ranbir Kapoor",
      "Ranveer Singh",
      "Shahid Kapoor",
      "Varun Dhawan",
      "Vicky Kaushal",
      "Rajkummar Rao",
      "Ayushmann Khurrana",
      "Saif Ali Khan",
      "Anil Kapoor",
      "John Abraham",
      "Sanjay Dutt",
      "Suniel Shetty",
      "Govinda",
      "Akshaye Khanna",
      "Emraan Hashmi",
      "Nawazuddin Siddiqui",
      "Pankaj Tripathi",
      "Rajesh Khanna",
      "Dharmendra",
      "Mithun Chakraborty",
      "Rishi Kapoor",
      "Irrfan Khan",
      "Nana Patekar",
    ],
  },

  /* =====================================================
       BOLLYWOOD ACTRESSES
    ===================================================== */

  {
    category: "Bollywood Actresses",
    words: [
      "Deepika Padukone",
      "Alia Bhatt",
      "Priyanka Chopra",
      "Katrina Kaif",
      "Kareena Kapoor",
      "Anushka Sharma",
      "Aishwarya Rai",
      "Kajol",
      "Madhuri Dixit",
      "Rani Mukerji",
      "Shraddha Kapoor",
      "Kriti Sanon",
      "Kiara Advani",
      "Kangana Ranaut",
      "Taapsee Pannu",
      "Vidya Balan",
      "Preity Zinta",
      "Juhi Chawla",
      "Sridevi",
      "Sonam Kapoor",
      "Janhvi Kapoor",
      "Disha Patani",
      "Bhumi Pednekar",
      "Parineeti Chopra",
      "Ananya Panday",
      "Sara Ali Khan",
      "Kajol",
      "Tabu",
      "Raveena Tandon",
      "Karisma Kapoor",
    ],
  },

  /* =====================================================
       SINGERS
    ===================================================== */

  {
    category: "Singers",
    words: [
      "Michael Jackson",
      "Taylor Swift",
      "Ed Sheeran",
      "Ariana Grande",
      "Bruno Mars",
      "Justin Bieber",
      "Billie Eilish",
      "The Weeknd",
      "Adele",
      "Rihanna",
      "Beyoncé",
      "Lady Gaga",
      "Eminem",
      "Drake",
      "Shakira",
      "Selena Gomez",
      "Katy Perry",
      "Justin Timberlake",
      "Britney Spears",
      "Elvis Presley",
      "Bob Marley",
      "Madonna",
      "Snoop Dogg",
      "Post Malone",
      "Harry Styles",
      "Dua Lipa",
      "Miley Cyrus",
      "Bruno Mars",
      "Alicia Keys",
      "Celine Dion",
    ],
  },

  /* =====================================================
       INDIAN SINGERS
    ===================================================== */

  {
    category: "Indian Singers",
    words: [
      "Arijit Singh",
      "Shreya Ghoshal",
      "Sonu Nigam",
      "A. R. Rahman",
      "Lata Mangeshkar",
      "Kishore Kumar",
      "Mohammed Rafi",
      "Udit Narayan",
      "Kumar Sanu",
      "Alka Yagnik",
      "Neha Kakkar",
      "Badshah",
      "Honey Singh",
      "Diljit Dosanjh",
      "Armaan Malik",
      "Jubin Nautiyal",
      "Atif Aslam",
      "KK",
      "Sunidhi Chauhan",
      "Shaan",
      "Mohit Chauhan",
      "Darshan Raval",
      "Shankar Mahadevan",
      "Sonu Nigam",
      "Rahat Fateh Ali Khan",
      "B Praak",
      "Anuv Jain",
      "King",
      "Vishal Dadlani",
      "Yo Yo Honey Singh",
    ],
  },

  /* =====================================================
       BANDS
    ===================================================== */

  {
    category: "Famous Bands",
    words: [
      "Queen",
      "The Beatles",
      "Nirvana",
      "Coldplay",
      "Linkin Park",
      "Imagine Dragons",
      "Maroon 5",
      "OneRepublic",
      "Metallica",
      "AC/DC",
      "Pink Floyd",
      "The Rolling Stones",
      "Arctic Monkeys",
      "Green Day",
      "Red Hot Chili Peppers",
      "Oasis",
      "ABBA",
      "Radiohead",
      "The Chainsmokers",
      "Twenty One Pilots",
      "Blackpink",
      "One Direction",
      "Backstreet Boys",
      "Jonas Brothers",
      "Bon Jovi",
      "Guns N' Roses",
      "The Eagles",
      "Foo Fighters",
      "U2",
      "The Who",
    ],
  },

  /* =====================================================
       CRICKETERS
    ===================================================== */

  {
    category: "Cricketers",
    words: [
      "Sachin Tendulkar",
      "Virat Kohli",
      "M. S. Dhoni",
      "Rohit Sharma",
      "Jasprit Bumrah",
      "Hardik Pandya",
      "Ravindra Jadeja",
      "Yuvraj Singh",
      "Kapil Dev",
      "Rahul Dravid",
      "Sourav Ganguly",
      "Virender Sehwag",
      "Sunil Gavaskar",
      "Anil Kumble",
      "Shubman Gill",
      "KL Rahul",
      "Rishabh Pant",
      "Suresh Raina",
      "AB de Villiers",
      "Chris Gayle",
      "Babar Azam",
      "Ben Stokes",
      "Joe Root",
      "Kane Williamson",
      "Pat Cummins",
      "David Warner",
      "Shane Warne",
      "Ricky Ponting",
      "Brett Lee",
      "Brian Lara",
    ],
  },

  /* =====================================================
       FOOTBALLERS
    ===================================================== */

  {
    category: "Footballers",
    words: [
      "Cristiano Ronaldo",
      "Lionel Messi",
      "Neymar",
      "Kylian Mbappe",
      "Erling Haaland",
      "David Beckham",
      "Zinedine Zidane",
      "Ronaldinho",
      "Mohamed Salah",
      "Robert Lewandowski",
      "Sergio Ramos",
      "Luka Modric",
      "Karim Benzema",
      "Harry Kane",
      "Kevin De Bruyne",
      "Wayne Rooney",
      "Thierry Henry",
      "Zlatan Ibrahimovic",
      "Luis Suarez",
      "Andres Iniesta",
      "Xavi",
      "Gerard Pique",
      "Sergio Aguero",
      "N'Golo Kante",
      "Paul Pogba",
      "Vinicius Jr.",
      "Jude Bellingham",
      "Sadio Mane",
      "Neymar",
      "Kaka",
    ],
  },

  /* =====================================================
       BASKETBALL PLAYERS
    ===================================================== */

  {
    category: "Basketball Players",
    words: [
      "Michael Jordan",
      "LeBron James",
      "Stephen Curry",
      "Kobe Bryant",
      "Shaquille O'Neal",
      "Kevin Durant",
      "Kyrie Irving",
      "James Harden",
      "Giannis Antetokounmpo",
      "Luka Doncic",
      "Nikola Jokic",
      "Magic Johnson",
      "Larry Bird",
      "Kawhi Leonard",
      "Anthony Davis",
      "Russell Westbrook",
      "Damian Lillard",
      "Dwyane Wade",
      "Carmelo Anthony",
      "Chris Paul",
      "Allen Iverson",
      "Dennis Rodman",
      "Tim Duncan",
      "Kevin Garnett",
      "Charles Barkley",
    ],
  },

  /* =====================================================
       F1 DRIVERS
    ===================================================== */

  {
    category: "F1 Drivers",
    words: [
      "Lewis Hamilton",
      "Max Verstappen",
      "Charles Leclerc",
      "Lando Norris",
      "Fernando Alonso",
      "Michael Schumacher",
      "Sebastian Vettel",
      "Ayrton Senna",
      "Kimi Raikkonen",
      "Nico Rosberg",
      "George Russell",
      "Carlos Sainz",
      "Sergio Perez",
      "Daniel Ricciardo",
      "Valtteri Bottas",
      "Felipe Massa",
      "Jenson Button",
      "Mika Hakkinen",
      "Alain Prost",
      "Nigel Mansell",
      "Juan Manuel Fangio",
      "Oscar Piastri",
      "Pierre Gasly",
      "Lance Stroll",
      "Esteban Ocon",
    ],
  },

  /* =====================================================
       YOUTUBERS
    ===================================================== */

  {
    category: "Famous YouTubers",
    words: [
      "MrBeast",
      "PewDiePie",
      "Markiplier",
      "Jacksepticeye",
      "KSI",
      "Logan Paul",
      "Jake Paul",
      "IShowSpeed",
      "Kai Cenat",
      "Ryan Trahan",
      "Dude Perfect",
      "Zach King",
      "Dream",
      "Casey Neistat",
      "Marques Brownlee",
      "LazarBeam",
      "DanTDM",
      "Pokimane",
      "Valkyrae",
      "Ninja",
      "Preston",
      "Sidemen",
      "Technoblade",
      "SSSniperWolf",
      "MrBeast",
    ],
  },

  /* =====================================================
       INDIAN YOUTUBERS
    ===================================================== */

  {
    category: "Indian YouTubers",
    words: [
      "CarryMinati",
      "Bhuvan Bam",
      "Ashish Chanchlani",
      "Techno Gamerz",
      "Total Gaming",
      "Triggered Insaan",
      "Mythpat",
      "Harsh Beniwal",
      "Round2hell",
      "Slayy Point",
      "Sourav Joshi",
      "Flying Beast",
      "Mumbiker Nikhil",
      "Technical Guruji",
      "BeastBoyShub",
      "Mortal",
      "Scout",
      "Dynamo",
      "Tanmay Bhat",
      "Samay Raina",
      "Zakir Khan",
      "Elvish Yadav",
      "Ashish Vidyarthi",
      "Dhruv Rathee",
      "Sandeep Maheshwari",
    ],
  },

  /* =====================================================
       COMEDIANS
    ===================================================== */

  {
    category: "Comedians",
    words: [
      "Mr. Bean",
      "Charlie Chaplin",
      "Jim Carrey",
      "Kevin Hart",
      "Chris Rock",
      "Rowan Atkinson",
      "Eddie Murphy",
      "Jack Black",
      "Steve Carell",
      "Adam Sandler",
      "Robin Williams",
      "George Carlin",
      "Dave Chappelle",
      "Conan O'Brien",
      "Jimmy Fallon",
      "Trevor Noah",
      "Kapil Sharma",
      "Zakir Khan",
      "Vir Das",
      "Biswa Kalyan Rath",
      "Tanmay Bhat",
      "Kanan Gill",
      "Amit Tandon",
      "Bharti Singh",
      "Johnny Lever",
    ],
  },

  /* =====================================================
       SCIENTISTS
    ===================================================== */

  {
    category: "Scientists",
    words: [
      "Albert Einstein",
      "Isaac Newton",
      "Nikola Tesla",
      "Stephen Hawking",
      "Marie Curie",
      "Charles Darwin",
      "Galileo Galilei",
      "Thomas Edison",
      "Alexander Graham Bell",
      "Louis Pasteur",
      "Gregor Mendel",
      "James Watt",
      "Robert Hooke",
      "Archimedes",
      "Aryabhata",
      "C. V. Raman",
      "A. P. J. Abdul Kalam",
      "Jagadish Chandra Bose",
      "Homi Bhabha",
      "Srinivasa Ramanujan",
      "Richard Feynman",
      "Alan Turing",
      "Stephen Hawking",
      "Johannes Kepler",
      "Michael Faraday",
    ],
  },

  /* =====================================================
       HISTORICAL FIGURES
    ===================================================== */

  {
    category: "Historical Figures",
    words: [
      "Mahatma Gandhi",
      "Napoleon Bonaparte",
      "Alexander the Great",
      "Julius Caesar",
      "Cleopatra",
      "Abraham Lincoln",
      "Nelson Mandela",
      "George Washington",
      "Queen Elizabeth II",
      "Winston Churchill",
      "Christopher Columbus",
      "Martin Luther King Jr.",
      "Joan of Arc",
      "Genghis Khan",
      "Mao Zedong",
      "Adolf Hitler",
      "Julius Caesar",
      "Leonardo da Vinci",
      "William Shakespeare",
      "Thomas Edison",
      "Subhas Chandra Bose",
      "Bhagat Singh",
      "Sardar Vallabhbhai Patel",
      "Rani Lakshmibai",
      "Chhatrapati Shivaji Maharaj",
    ],
  },

  /* =====================================================
       BUSINESSMEN
    ===================================================== */

  {
    category: "Business Personalities",
    words: [
      "Elon Musk",
      "Bill Gates",
      "Steve Jobs",
      "Jeff Bezos",
      "Mark Zuckerberg",
      "Warren Buffett",
      "Ratan Tata",
      "Mukesh Ambani",
      "Gautam Adani",
      "Richard Branson",
      "Jack Ma",
      "Larry Page",
      "Sergey Brin",
      "Sundar Pichai",
      "Satya Nadella",
      "Tim Cook",
      "Jensen Huang",
      "Walt Disney",
      "Henry Ford",
      "Sam Walton",
      "Dhirubhai Ambani",
      "Anand Mahindra",
      "Narayana Murthy",
      "Azim Premji",
      "Indra Nooyi",
    ],
  },

  /* =====================================================
       AUTHORS
    ===================================================== */

  {
    category: "Authors",
    words: [
      "William Shakespeare",
      "J. K. Rowling",
      "George R. R. Martin",
      "George Orwell",
      "Mark Twain",
      "Agatha Christie",
      "Stephen King",
      "Dan Brown",
      "J. R. R. Tolkien",
      "Ernest Hemingway",
      "Charles Dickens",
      "Jane Austen",
      "Leo Tolstoy",
      "Fyodor Dostoevsky",
      "Chetan Bhagat",
      "Ruskin Bond",
      "R. K. Narayan",
      "Rabindranath Tagore",
      "Dr. Seuss",
      "Enid Blyton",
      "Paulo Coelho",
      "Roald Dahl",
      "Arthur Conan Doyle",
      "Victor Hugo",
      "Oscar Wilde",
    ],
  },

  /* =====================================================
       MOVIES
    ===================================================== */

  {
    category: "Famous Movies",
    words: [
      "Titanic",
      "Avatar",
      "Avengers",
      "Iron Man",
      "Spider-Man",
      "The Dark Knight",
      "Inception",
      "Interstellar",
      "Jurassic Park",
      "The Matrix",
      "Harry Potter",
      "The Lion King",
      "Frozen",
      "Toy Story",
      "Finding Nemo",
      "The Godfather",
      "Gladiator",
      "Joker",
      "Oppenheimer",
      "Barbie",
      "Top Gun",
      "Home Alone",
      "Pirates of the Caribbean",
      "The Lord of the Rings",
      "Star Wars",
      "Rocky",
      "Forrest Gump",
      "Mission Impossible",
      "Fast & Furious",
      "The Hangover",
    ],
  },

  /* =====================================================
       BOLLYWOOD MOVIES
    ===================================================== */

  {
    category: "Bollywood Movies",
    words: [
      "3 Idiots",
      "Dangal",
      "Sholay",
      "Lagaan",
      "Dilwale Dulhania Le Jayenge",
      "Kabhi Khushi Kabhie Gham",
      "Zindagi Na Milegi Dobara",
      "Chennai Express",
      "Pathaan",
      "Jawan",
      "Gadar",
      "Bajrangi Bhaijaan",
      "PK",
      "Sultan",
      "War",
      "Krrish",
      "Don",
      "Kabir Singh",
      "Barfi!",
      "Yeh Jawaani Hai Deewani",
      "Bhool Bhulaiyaa",
      "Welcome",
      "Hera Pheri",
      "Munna Bhai M.B.B.S.",
      "Drishyam",
    ],
  },

  /* =====================================================
       TV SHOWS
    ===================================================== */

  {
    category: "TV Shows",
    words: [
      "Friends",
      "Breaking Bad",
      "Game of Thrones",
      "The Simpsons",
      "Stranger Things",
      "The Office",
      "Money Heist",
      "Wednesday",
      "Sherlock",
      "Peaky Blinders",
      "The Big Bang Theory",
      "How I Met Your Mother",
      "The Walking Dead",
      "Squid Game",
      "Prison Break",
      "House of the Dragon",
      "The Boys",
      "Modern Family",
      "The Flash",
      "Lucifer",
      "Cobra Kai",
      "Black Mirror",
      "Suits",
      "The Vampire Diaries",
      "Brooklyn Nine-Nine",
    ],
  },

  /* =====================================================
       INDIAN TV SHOWS
    ===================================================== */

  {
    category: "Indian TV Shows",
    words: [
      "Taarak Mehta Ka Ooltah Chashmah",
      "CID",
      "The Kapil Sharma Show",
      "Indian Idol",
      "Bigg Boss",
      "Kaun Banega Crorepati",
      "Shark Tank India",
      "Khatron Ke Khiladi",
      "Roadies",
      "Splitsvilla",
      "Crime Patrol",
      "Comedy Nights with Kapil",
      "Dance India Dance",
      "Sa Re Ga Ma Pa",
      "MasterChef India",
      "Pavitra Rishta",
      "Yeh Rishta Kya Kehlata Hai",
      "Sarabhai vs Sarabhai",
      "Ramayan",
      "Mahabharat",
    ],
  },

  /* =====================================================
       SPORTS
    ===================================================== */

  {
    category: "Sports",
    words: [
      "Cricket",
      "Football",
      "Basketball",
      "Tennis",
      "Badminton",
      "Boxing",
      "Wrestling",
      "Hockey",
      "Swimming",
      "Golf",
      "Volleyball",
      "Baseball",
      "Table Tennis",
      "Formula 1",
      "Kabaddi",
      "Chess",
      "Athletics",
      "Cycling",
      "Gymnastics",
      "Archery",
      "Karate",
      "Skating",
      "Surfing",
      "Skiing",
      "Rugby",
    ],
  },

  /* =====================================================
       COUNTRIES
    ===================================================== */

  {
    category: "Countries",
    words: [
      "India",
      "United States",
      "United Kingdom",
      "Canada",
      "Australia",
      "Japan",
      "China",
      "South Korea",
      "France",
      "Germany",
      "Italy",
      "Spain",
      "Brazil",
      "Argentina",
      "Mexico",
      "Russia",
      "Dubai",
      "Singapore",
      "Thailand",
      "Switzerland",
      "Nepal",
      "Pakistan",
      "Sri Lanka",
      "New Zealand",
      "South Africa",
      "Egypt",
      "Turkey",
      "Greece",
      "Saudi Arabia",
      "Indonesia",
    ],
  },

  /* =====================================================
       CITIES
    ===================================================== */

  {
    category: "Famous Cities",
    words: [
      "Mumbai",
      "Delhi",
      "New York",
      "London",
      "Paris",
      "Tokyo",
      "Dubai",
      "Singapore",
      "Los Angeles",
      "Las Vegas",
      "Sydney",
      "Toronto",
      "Rome",
      "Barcelona",
      "Madrid",
      "Berlin",
      "Seoul",
      "Bangkok",
      "Moscow",
      "Venice",
      "Amsterdam",
      "Hong Kong",
      "Istanbul",
      "Pune",
      "Bengaluru",
      "Kolkata",
      "Chennai",
      "Hyderabad",
      "Jaipur",
      "Goa",
    ],
  },

  /* =====================================================
       LANDMARKS
    ===================================================== */

  {
    category: "Famous Landmarks",
    words: [
      "Taj Mahal",
      "Eiffel Tower",
      "Statue of Liberty",
      "Burj Khalifa",
      "Great Wall of China",
      "Big Ben",
      "Colosseum",
      "Pyramids of Giza",
      "Sydney Opera House",
      "Golden Gate Bridge",
      "Leaning Tower of Pisa",
      "Christ the Redeemer",
      "Mount Everest",
      "Stonehenge",
      "Niagara Falls",
      "Empire State Building",
      "Buckingham Palace",
      "Machu Picchu",
      "Petra",
      "Times Square",
      "Hollywood Sign",
      "Red Fort",
      "India Gate",
      "Gateway of India",
      "Sagrada Familia",
    ],
  },

  /* =====================================================
       BRANDS
    ===================================================== */

  {
    category: "Famous Brands",
    words: [
      "Nike",
      "Adidas",
      "Puma",
      "Apple",
      "Samsung",
      "Sony",
      "Coca-Cola",
      "Pepsi",
      "McDonald's",
      "KFC",
      "Starbucks",
      "BMW",
      "Mercedes-Benz",
      "Toyota",
      "Honda",
      "Ferrari",
      "Lamborghini",
      "Tesla",
      "Gucci",
      "Louis Vuitton",
      "Prada",
      "Rolex",
      "Lego",
      "IKEA",
      "Netflix",
      "Disney",
      "Amazon",
      "Google",
      "Microsoft",
      "Adidas",
    ],
  },

  /* =====================================================
       FAST FOOD
    ===================================================== */

  {
    category: "Fast Food",
    words: [
      "Pizza",
      "Burger",
      "French Fries",
      "Hot Dog",
      "Fried Chicken",
      "Sandwich",
      "Tacos",
      "Nuggets",
      "Pasta",
      "Donut",
      "Popcorn",
      "Nachos",
      "Momos",
      "Pav Bhaji",
      "Vada Pav",
      "Samosa",
      "Pani Puri",
      "Dosa",
      "Spring Roll",
      "Shawarma",
      "Kebab",
      "Biryani",
      "Ice Cream",
      "Chocolate",
      "Pancakes",
    ],
  },

  /* =====================================================
       INDIAN FOOD
    ===================================================== */

  {
    category: "Indian Food",
    words: [
      "Biryani",
      "Butter Chicken",
      "Paneer Tikka",
      "Vada Pav",
      "Pav Bhaji",
      "Samosa",
      "Dosa",
      "Idli",
      "Pani Puri",
      "Chole Bhature",
      "Rajma Chawal",
      "Dal Makhani",
      "Aloo Paratha",
      "Palak Paneer",
      "Tandoori Chicken",
      "Misal Pav",
      "Poha",
      "Dhokla",
      "Kheer",
      "Gulab Jamun",
      "Jalebi",
      "Rasgulla",
      "Lassi",
      "Naan",
      "Chicken Tikka",
    ],
  },

  /* =====================================================
       CARS
    ===================================================== */

  {
    category: "Famous Cars",
    words: [
      "Ferrari",
      "Lamborghini",
      "Porsche",
      "BMW",
      "Mercedes",
      "Audi",
      "Tesla",
      "Toyota",
      "Honda",
      "Ford Mustang",
      "Jeep",
      "Range Rover",
      "Rolls-Royce",
      "Bentley",
      "Bugatti",
      "McLaren",
      "Aston Martin",
      "Volkswagen",
      "Nissan",
      "Hyundai",
      "Mahindra Thar",
      "Tata Nexon",
      "Maruti Swift",
      "Toyota Fortuner",
      "Land Rover",
    ],
  },

  /* =====================================================
       DRINKS
    ===================================================== */

  {
    category: "Drinks",
    words: [
      "Coca-Cola",
      "Pepsi",
      "Sprite",
      "Fanta",
      "Red Bull",
      "Mountain Dew",
      "7UP",
      "Mirinda",
      "Thumbs Up",
      "Limca",
      "Frooti",
      "Maaza",
      "Slice",
      "Appy Fizz",
      "Coconut Water",
      "Lemonade",
      "Milkshake",
      "Coffee",
      "Tea",
      "Hot Chocolate",
      "Orange Juice",
      "Apple Juice",
      "Mango Juice",
      "Lassi",
      "Milk",
    ],
  },

  /* =====================================================
       FAMOUS PLACES
    ===================================================== */

  {
    category: "Tourist Places",
    words: [
      "Taj Mahal",
      "Goa",
      "Dubai",
      "Paris",
      "New York",
      "London",
      "Switzerland",
      "Maldives",
      "Bali",
      "Thailand",
      "Singapore",
      "Tokyo",
      "Las Vegas",
      "Hawaii",
      "Australia",
      "New Zealand",
      "Mount Everest",
      "Niagara Falls",
      "Disneyland",
      "Universal Studios",
      "Venice",
      "Rome",
      "Barcelona",
      "Istanbul",
      "Manali",
    ],
  },

  /* =====================================================
       DISNEY CHARACTERS
    ===================================================== */

  {
    category: "Disney Characters",
    words: [
      "Mickey Mouse",
      "Donald Duck",
      "Minnie Mouse",
      "Goofy",
      "Cinderella",
      "Snow White",
      "Elsa",
      "Anna",
      "Simba",
      "Mufasa",
      "Aladdin",
      "Genie",
      "Ariel",
      "Rapunzel",
      "Tinker Bell",
      "Peter Pan",
      "Woody",
      "Buzz Lightyear",
      "Stitch",
      "Winnie the Pooh",
      "Dumbo",
      "Bambi",
      "Pocahontas",
      "Moana",
      "Hercules",
    ],
  },

  /* =====================================================
       SUPERHEROES
    ===================================================== */

  {
    category: "Superheroes",
    words: [
      "Spider-Man",
      "Iron Man",
      "Batman",
      "Superman",
      "Captain America",
      "Thor",
      "Hulk",
      "Wonder Woman",
      "Black Panther",
      "Flash",
      "Aquaman",
      "Doctor Strange",
      "Deadpool",
      "Wolverine",
      "Captain Marvel",
      "Black Widow",
      "Hawkeye",
      "Ant-Man",
      "Green Lantern",
      "Supergirl",
      "Shazam",
      "Cyborg",
      "Daredevil",
      "Green Arrow",
      "Batgirl",
    ],
  },

  /* =====================================================
       VILLAINS
    ===================================================== */

  {
    category: "Famous Villains",
    words: [
      "Joker",
      "Thanos",
      "Darth Vader",
      "Voldemort",
      "Loki",
      "Ultron",
      "Green Goblin",
      "Venom",
      "Magneto",
      "Maleficent",
      "Cruella",
      "Hannibal Lecter",
      "Sauron",
      "Lord Voldemort",
      "Scar",
      "Hades",
      "Captain Hook",
      "Ursula",
      "Davy Jones",
      "Agent Smith",
      "Bane",
      "Lex Luthor",
      "Dr. Octopus",
      "Harley Quinn",
      "Moriarty",
    ],
  },

  /* =====================================================
       FAMOUS FICTIONAL CHARACTERS
    ===================================================== */

  {
    category: "Famous Characters",
    words: [
      "Harry Potter",
      "Sherlock Holmes",
      "James Bond",
      "Mr. Bean",
      "Jack Sparrow",
      "Forrest Gump",
      "Rocky Balboa",
      "John Wick",
      "Indiana Jones",
      "Homer Simpson",
      "Bart Simpson",
      "Peter Griffin",
      "Wednesday Addams",
      "Walter White",
      "Saul Goodman",
      "Tony Stark",
      "Bruce Wayne",
      "Clark Kent",
      "Peter Parker",
      "Darth Vader",
      "Luke Skywalker",
      "Yoda",
      "Gandalf",
      "Frodo Baggins",
      "Gollum",
    ],
  },

  /* =====================================================
       RESTAURANTS
    ===================================================== */

  {
    category: "Famous Restaurants",
    words: [
      "McDonald's",
      "KFC",
      "Burger King",
      "Pizza Hut",
      "Domino's",
      "Subway",
      "Starbucks",
      "Taco Bell",
      "Dunkin'",
      "Wendy's",
      "Popeyes",
      "Five Guys",
      "Papa John's",
      "Tim Hortons",
      "Dairy Queen",
      "Baskin-Robbins",
      "Haldiram's",
      "Barbeque Nation",
      "Bikanervala",
      "Wow! Momo",
    ],
  },

  /* =====================================================
       INVENTORS
    ===================================================== */

  {
    category: "Famous Inventors",
    words: [
      "Thomas Edison",
      "Nikola Tesla",
      "Alexander Graham Bell",
      "Wright Brothers",
      "James Watt",
      "Benjamin Franklin",
      "Johannes Gutenberg",
      "Tim Berners-Lee",
      "Eli Whitney",
      "George Stephenson",
      "Samuel Morse",
      "Guglielmo Marconi",
      "Henry Ford",
      "James Dyson",
      "Steve Jobs",
      "Alexander Fleming",
      "Louis Pasteur",
      "Galileo Galilei",
      "Leonardo da Vinci",
      "Isaac Newton",
    ],
  },

  /* =====================================================
       FAMOUS ATHLETES
    ===================================================== */

  {
    category: "Famous Athletes",
    words: [
      "Usain Bolt",
      "Michael Phelps",
      "Serena Williams",
      "Roger Federer",
      "Rafael Nadal",
      "Novak Djokovic",
      "Simone Biles",
      "Michael Jordan",
      "LeBron James",
      "Cristiano Ronaldo",
      "Lionel Messi",
      "Sachin Tendulkar",
      "Virat Kohli",
      "M. S. Dhoni",
      "Neeraj Chopra",
      "P. V. Sindhu",
      "Mary Kom",
      "Sania Mirza",
      "Tiger Woods",
      "Muhammad Ali",
      "Mike Tyson",
      "Conor McGregor",
      "David Beckham",
      "Lewis Hamilton",
      "Max Verstappen",
    ],
  },

  /* =====================================================
       WORLD LEADERS / POLITICAL FIGURES
       FAMOUS HISTORICAL/PUBLIC NAMES
    ===================================================== */

  {
    category: "World Leaders",
    words: [
      "Mahatma Gandhi",
      "Nelson Mandela",
      "Abraham Lincoln",
      "Barack Obama",
      "Donald Trump",
      "Winston Churchill",
      "George Washington",
      "Vladimir Putin",
      "Xi Jinping",
      "Queen Elizabeth II",
      "Julius Caesar",
      "Napoleon Bonaparte",
      "Martin Luther King Jr.",
      "Mao Zedong",
      "John F. Kennedy",
      "Jawaharlal Nehru",
      "Subhas Chandra Bose",
      "Sardar Patel",
      "Winston Churchill",
      "Mother Teresa",
    ],
  },
];
